author: mslinn
compress_html:
  blanklines: false
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  profile: false
  startings: [html, head, body]
domain: www.mslinn.com
email: bogus@example.com
exclude:  # Wildcards are not supported yet https://github.com/jekyll/jekyll-watch/pull/93
  - .git
  - .github
  - .gitignore
  - .jekyll-cache
  - .jekyll-metadata
  - .ruby-version
  - .vscode
  - BingSiteAuth.xml
  - Gemfile
  - Gemfile.lock
  - README.md
ignore_theme_config: true
liquid:
  error_mode: strict
  # strict_filters: true
  # strict_variables: true
livereload_ignore: [ 'assets/images/qrcodes/*', '/assets/images/qrcodes/*' ]
plugin_loggers:
  PluginMetaLogger: info
  CleanHook: warn
  DocumentHooks: warn
  MyBlock: warn
  JekyllQRCodes::QRCodeEnrichmentData: info
  QRCodeGenerator: info
  QRPath: debug
  SiteHooks: warn
permalink: "/blog/:year/:month/:day/:title:output_ext"
plugins: # Use file name of the plugin entry point, not the gem name
  - jekyll
  - jekyll_plugin_logger
qrcode:
  fg_color: ':yellow'
sass:
  style: compressed
title: QR Code Generation Demonstration
url: https://bogus.jekylldemo.com
