source 'https://rubygems.org'

gem 'jekyll', '>= 4.3.3'
gem 'json', '=2.6.3' # Remove this entry when Jekyll 4.3.3+ is released

group :jekyll_plugins do
  # gem 'html-proofer'
  gem 'jekyll-assets', git: 'https://github.com/envygeeks/jekyll-assets'
  gem 'jekyll-environment-variables'
  gem 'jekyll_plugin_logger'
  gem 'jekyll_qr_generator', path: '../'
  gem 'jekyll-tagging'
end

group :test, :development do
  gem 'debug', '>= 1.0.0', require: false
  gem 'pry', '>= 0.14.2'
  gem 'rake', require: false
  gem 'rspec', require: false
  gem 'rubocop', require: false
  gem 'rubocop-jekyll', '>= 0.13.0', require: false
  gem 'rubocop-md', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rake', require: false
  gem 'rubocop-rspec', require: false
end
